### PR TITLE
kqueue(2)-based Selector implementation breaks on FreeBSD 12 due to ABI changes

### PR DESCRIPTION
**Pull request by Low-power**
FreeBSD 12 introduced an [incompatible change](https://svnweb.freebsd.org/base/head/sys/sys/event.h?r1=320043&r2=320042&pathrev=320043) to the `struct kevent`, in [revision 320043](https://svnweb.freebsd.org/base?view=revision&revision=320043); although binary compatibility is maintained in both kernel and C library, by supporting the old system call number (363) and the old versioned symbol (`kevent@FBSD_1.0`), this change does break JNR ENXIO, because it doesn't support versioned symbols and always use the default version, which is the latest version `kevent@@FBSD_1.5` in FreeBSD 12 `libc.so.7`.

As a result, when more than 1 event happend after a **kevent(2)** call (`nready > 1`), this Selector implementation would either miss some events on a 64-bit FreeBSD 12+ system because it would read file descriptors from the newly added `ext` field, which are currently, all zeros, or miss all events but the first on a 32-bit FreeBSD 12+ system.

This workaround looks like a dirty hack, but I couldn't find a better way to implement it.

### CODE REVIEW

**Comment by Low-power** [comment]
So jnr-enxio will have to be changed to use jnr-posix, rather than importing C symbols by its own? Another issue is the **kqueue(2)** API is BSD-specific, not in POSIX; so I don't think it should be added to jnr-posix.

**Comment by headius** [comment]
@Low-power My first thought is that we should try to use the same logic as jnr-posix to determine we are on FreeBSD 12, but if that needs changes in jnr-posix then we can move forward with this PR for now. And yes, I think enxio is the right place to have all these selector API wrappers.

**Comment by Low-power** [comment]
I think may be this platform-specific logic (running `freebsd-version -u`, then prasing the version number) should be moved into jnr-ffi, as a new API, since that library already providing some basic platform detection mechanisms, in `jnr.ffi.Platform`; then both jnr-enxio and jnr-posix could make use of it.

**Comment by headius** [comment]
> should be moved into jnr-ffi, as a new AP

@Low-power Agreed! There's already some platform-detection logic in there... we just need to formalize the API and move the hacks out of jnr-posix.

I will merge what you have for now and we can look at that as a separate project.

**Pull request merged**
