### PR TITLE
Throw an IOException if native close() fails.

### PR DESCRIPTION
**Pull request by risenberg**
close() failure may happen in case of a double close on same fd, which speaks of logical errors in code.

### CODE REVIEW

**Comment by risenberg** [comment]
Any chance for this to get into a release?

**Comment by headius** [comment]
Sorry I had not noticed this one...reviewing.

**Comment by headius** [comment]
> I'm wondering if we shouldn't make our own type

...of IOException, that is.

**Comment by headius** [comment]
We'll go with this for now.

**Pull request merged**
